#!/usr/bin/env bash
set -euo pipefail

REPO_DIR=${WD_NOTABILITY_REPO_DIR:-"$HOME/wd-notability"}
VENV_DIR=${WD_NOTABILITY_VENV_DIR:-"$HOME/venv/wd-notability"}
TOOLFORGE_IMAGE=${WD_NOTABILITY_TOOLFORGE_IMAGE:-python3.11}
JOB_NAME=${WD_NOTABILITY_INIT_JOB_NAME:-wd-notability-bootstrap}
LOOKUP_BACKEND=${WD_NOTABILITY_LOOKUP_BACKEND:-mariadb}
LOOKUP_DATABASE=${WD_NOTABILITY_LOOKUP_DATABASE:-wd_notability}
LOOKUP_HOST=${WD_NOTABILITY_LOOKUP_HOST:-tools.db.svc.wikimedia.cloud}
CACHE_BACKEND=${WD_NOTABILITY_CACHE_BACKEND:-mariadb}
CACHE_DATABASE=${WD_NOTABILITY_CACHE_DATABASE:-wd_notability}
CACHE_HOST=${WD_NOTABILITY_CACHE_HOST:-tools.db.svc.wikimedia.cloud}
CACHE_DEFAULTS_FILE=${WD_NOTABILITY_CACHE_DEFAULTS_FILE:-"$HOME/replica.my.cnf"}

submit() {
  local command="$1"
  toolforge jobs run "$JOB_NAME" \
    --image "$TOOLFORGE_IMAGE" \
    --command "$command"
}

submit "cd \"$REPO_DIR\" && \
PYTHONPATH=\"$REPO_DIR\" \
WD_NOTABILITY_CACHE_BACKEND=\"$CACHE_BACKEND\" \
WD_NOTABILITY_CACHE_DATABASE=\"$CACHE_DATABASE\" \
WD_NOTABILITY_CACHE_HOST=\"$CACHE_HOST\" \
WD_NOTABILITY_CACHE_DEFAULTS_FILE=\"$CACHE_DEFAULTS_FILE\" \
WD_NOTABILITY_LOOKUP_BACKEND=\"$LOOKUP_BACKEND\" \
WD_NOTABILITY_LOOKUP_DATABASE=\"$LOOKUP_DATABASE\" \
WD_NOTABILITY_LOOKUP_HOST=\"$LOOKUP_HOST\" \
\"$VENV_DIR/bin/python\" scripts/build_namespace_cache.py && \
PYTHONPATH=\"$REPO_DIR\" \
WD_NOTABILITY_LOOKUP_BACKEND=\"$LOOKUP_BACKEND\" \
WD_NOTABILITY_LOOKUP_DATABASE=\"$LOOKUP_DATABASE\" \
WD_NOTABILITY_LOOKUP_HOST=\"$LOOKUP_HOST\" \
\"$VENV_DIR/bin/python\" scripts/build_property_cache.py && \
PYTHONPATH=\"$REPO_DIR\" \
WD_NOTABILITY_LOOKUP_BACKEND=\"$LOOKUP_BACKEND\" \
WD_NOTABILITY_LOOKUP_DATABASE=\"$LOOKUP_DATABASE\" \
WD_NOTABILITY_LOOKUP_HOST=\"$LOOKUP_HOST\" \
\"$VENV_DIR/bin/python\" scripts/build_osm_cache.py && \
PYTHONPATH=\"$REPO_DIR\" \
WD_NOTABILITY_LOOKUP_BACKEND=\"$LOOKUP_BACKEND\" \
WD_NOTABILITY_LOOKUP_DATABASE=\"$LOOKUP_DATABASE\" \
WD_NOTABILITY_LOOKUP_HOST=\"$LOOKUP_HOST\" \
\"$VENV_DIR/bin/python\" scripts/build_sdc_cache.py && \
PYTHONPATH=\"$REPO_DIR\" \
WD_NOTABILITY_LOOKUP_BACKEND=\"$LOOKUP_BACKEND\" \
WD_NOTABILITY_LOOKUP_DATABASE=\"$LOOKUP_DATABASE\" \
WD_NOTABILITY_LOOKUP_HOST=\"$LOOKUP_HOST\" \
\"$VENV_DIR/bin/python\" scripts/build_wikisub_cache.py && \
PYTHONPATH=\"$REPO_DIR\" \
    WD_NOTABILITY_LOOKUP_BACKEND=\"$LOOKUP_BACKEND\" \
    WD_NOTABILITY_LOOKUP_DATABASE=\"$LOOKUP_DATABASE\" \
    WD_NOTABILITY_LOOKUP_HOST=\"$LOOKUP_HOST\" \
    WD_NOTABILITY_CACHE_BACKEND=\"$CACHE_BACKEND\" \
    WD_NOTABILITY_CACHE_DATABASE=\"$CACHE_DATABASE\" \
    WD_NOTABILITY_CACHE_HOST=\"$CACHE_HOST\" \
    WD_NOTABILITY_CACHE_DEFAULTS_FILE=\"$CACHE_DEFAULTS_FILE\" \
    \"$VENV_DIR/bin/python\" scripts/reset_main_cache.py"
